version: 2
updates:
  # Root directory Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "yue4521"
    assignees:
      - "yue4521"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # ML directory Python packages (pyproject.toml)
  - package-ecosystem: "pip"
    directory: "/ml"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "yue4521"
    assignees:
      - "yue4521"
    commit-message:
      prefix: "deps(ml)"
      include: "scope"
    labels:
      - "dependencies"
      - "ml"
      - "python"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Root directory npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "yue4521"
    assignees:
      - "yue4521"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Client directory npm packages
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "yue4521"
    assignees:
      - "yue4521"
    commit-message:
      prefix: "deps(client)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore indirect dependencies that can't be safely updated
    ignore:
      - dependency-name: "nth-check"
        versions: ["< 2.0.1"]
      - dependency-name: "postcss"
        versions: ["< 8.4.31"]
      - dependency-name: "webpack-dev-server"
        versions: ["<= 5.2.0"]
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Server directory npm packages
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "yue4521"
    assignees:
      - "yue4521"
    commit-message:
      prefix: "deps(server)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "javascript"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"