version: 2

# 共通設定定義 - YAMLアンカーによる重複削減
x-common-schedule: &common-schedule
  interval: "weekly"
  day: "monday"
  time: "09:00"
  timezone: "Asia/Tokyo"

x-common-reviewers: &common-reviewers
  - "yue4521"

x-common-assignees: &common-assignees
  - "yue4521"

x-common-dependency-types: &common-dependency-types
  - dependency-type: "direct"
  - dependency-type: "indirect"

x-common-groups: &common-groups
  production-dependencies:
    dependency-type: "production"
    update-types:
      - "major"
      - "minor"
      - "patch"
  development-dependencies:
    dependency-type: "development"
    update-types:
      - "minor"
      - "patch"

updates:
  # ルートディレクトリ Python パッケージ管理
  - package-ecosystem: "pip"
    directory: "/"
    schedule: *common-schedule
    open-pull-requests-limit: 5
    reviewers: *common-reviewers
    assignees: *common-assignees
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    allow: *common-dependency-types
    groups: *common-groups

  # MLディレクトリ Python パッケージ管理 (pyproject.toml)
  - package-ecosystem: "pip"
    directory: "/ml"
    schedule: *common-schedule
    open-pull-requests-limit: 3
    reviewers: *common-reviewers
    assignees: *common-assignees
    commit-message:
      prefix: "deps(ml)"
      include: "scope"
    labels:
      - "dependencies"
      - "ml"
      - "python"
    allow: *common-dependency-types
    groups: *common-groups

  # ルートディレクトリ npm パッケージ管理
  - package-ecosystem: "npm"
    directory: "/"
    schedule: *common-schedule
    open-pull-requests-limit: 5
    reviewers: *common-reviewers
    assignees: *common-assignees
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    allow: *common-dependency-types
    groups: *common-groups

  # クライアントディレクトリ npm パッケージ管理
  - package-ecosystem: "npm"
    directory: "/client"
    schedule: *common-schedule
    open-pull-requests-limit: 3
    reviewers: *common-reviewers
    assignees: *common-assignees
    commit-message:
      prefix: "deps(client)"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    allow: *common-dependency-types
    # 安全にアップデートできない間接依存関係を無視
    ignore:
      - dependency-name: "nth-check"
        versions: ["< 2.0.1"]
      - dependency-name: "postcss"
        versions: ["< 8.4.31"]
      - dependency-name: "webpack-dev-server"
        versions: ["<= 5.2.0"]
    groups: *common-groups

  # サーバーディレクトリ npm パッケージ管理
  - package-ecosystem: "npm"
    directory: "/server"
    schedule: *common-schedule
    open-pull-requests-limit: 3
    reviewers: *common-reviewers
    assignees: *common-assignees
    commit-message:
      prefix: "deps(server)"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    allow: *common-dependency-types
    groups: *common-groups