version: 2
updates:
  # ルートレベルのnpmパッケージ
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # サーバーのnpmパッケージ
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # クライアントのnpmパッケージ
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  # Python パッケージ
  - package-ecosystem: "pip"
    directory: "/ml"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5